person/config/routes.rb
Person::Application.routes.draw do
  resources :personals

end

person/app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :personals, :through => :personalcategory
  has_many :personal_category
end

person/app/models/personal.rb
class Personal < ActiveRecord::Base
  attr_accessible :address, :age, :birthday, :hight, :name, :weight
  has_many :personalcategory
end

person/app/models/personal_category.rb
class PersonalCategory < ActiveRecord::Base
  # attr_accessible :title, :body
  belong_to :personal
  belong_to :category
end

person/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

person/app/controllers/personals_controller.rb
# -*- coding: utf-8 -*-
class PersonalsController < ApplicationController
  # GET /personals
  # GET /personals.json
  def index
    @personals = Personal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @personals }
    end
  end

  # GET /personals/1
  # GET /personals/1.json
  def show
    @personal = Personal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @personal }
    end
  end

  # GET /personals/new
  # GET /personals/new.json
  def new
    @personal = Personal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @personal }
    end
  end

  # GET /personals/1/edit
  def edit
    @personal = Personal.find(params[:id])
  end

  # POST /personals
  # POST /personals.json
  def create
    @personal = Personal.new(params[:personal])

    respond_to do |format|
      if @personal.save
        format.html { redirect_to @personal, :notice => 'Personal was successfully created.' }
        format.json { render :json => @personal, :status => :created, :location => @personal }
      else
        format.html { render :action => "new" }
        format.json { render :json => @personal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /personals/1
  # PUT /personals/1.json
  def update
    @personal = Personal.find(params[:id])

    respond_to do |format|
      if @personal.update_attributes(params[:personal])
        format.html { redirect_to @personal, :notice => '更新成功' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @personal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /personals/1
  # DELETE /personals/1.json
  def destroy
    @personal = Personal.find(params[:id])
    @personal.destroy

    respond_to do |format|
      format.html { redirect_to personals_url }
      format.json { head :no_content }
    end
  end

  def search
    @personal = Personal.all
    render :serach
  end
end

person/app/helpers/application_helper.rb
module ApplicationHelper
end

person/app/helpers/personals_helper.rb
module PersonalsHelper
end

person/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Person</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

person/app/views/personals/_form.html.erb
<%= form_for(@personal) do |f| %>
  <% if @personal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal.errors.count, "error") %> prohibited this personal from being saved:</h2>

      <ul>
      <% @personal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名前 %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :住所 %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :誕生日 %><br />
    <%= f.date_select :birthday, {:start_year => 1900, :end_year => Date.today.year, :use_month_numbers => true} %>
  </div>
  <div class="field">
    <%= f.label :年齢 %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :身長 %><br />
    <%= f.text_field :hight %>
  </div>
  <div class="field">
    <%= f.label :体重 %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit "内容更新" %>
  </div>
<% end %>

person/app/views/personals/edit.html.erb
<h1>内容編集</h1>

<%= render 'form' %>

<%= link_to '表示', @personal %> |
<%= link_to '一覧', personals_path %>

person/app/views/personals/index.html.erb
<h1>名簿登録</h1> 

<table>
  <tr>
    <th>名前</th>
    <th>住所</th>
    <th>誕生日</th>
    <th>年齢</th>
    <th>身長</th>
    <th>体重</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personals.each do |personal| %>
  <tr>
    <td><%= personal.name %></td>
    <td><%= personal.address %></td>
    <td><%= personal.birthday %></td>
    <td><%= personal.age %></td>
    <td><%= personal.hight %></td>
    <td><%= personal.weight %></td>
    <td><%= link_to '表示', personal %></td>
    <td><%= link_to '編集', edit_personal_path(personal) %></td>
    <td><%= link_to '削除', personal, :confirm => '本当によろしいですか？', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新規登録', new_personal_path %>

person/app/views/personals/new.html.erb
<h1>新規登録</h1>

<%= render 'form' %>

<%= link_to '一覧', personals_path %>

person/app/views/personals/search.html.erb
<h1>条件検索</h1>

person/app/views/personals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>名前:</b>
  <%= @personal.name %>
</p>

<p>
  <b>住所:</b>
  <%= @personal.address %>
</p>

<p>
  <b>生年月日:</b>
  <%= @personal.birthday %>
</p>

<p>
  <b>年齢:</b>
  <%= @personal.age %>
</p>

<p>
  <b>身長:</b>
  <%= @personal.hight %>
</p>

<p>
  <b>体重:</b>
  <%= @personal.weight %>
</p>


<%= link_to '編集', edit_personal_path(@personal) %> |
<%= link_to '一覧', personals_path %>